# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialSharing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialSharing
  pod 'FBSDKShareKit', '~> 4.38.1'
  pod 'FBSDKLoginKit', '~> 4.38.1'
  pod 'FBSDKCoreKit', '~> 4.38.1'
  
  pod 'TwitterKit', '~> 3.4'
  pod 'InstagramLogin', '~> 1.3'
  
end
